x = input('Digite algo: ')
print(x.isalpha())
print(x.isalnum())
print(x.isascii())
print(x.isdecimal())
print(x.isdigit())
print(x.isidentifier())
print(x.islower())
print(x.isnumeric())
print(x.isprintable())
print(x.isspace())
print(x.istitle())
print(x.isupper())