nome = input('Digite seu nome: ')
print('Olá {:20}!'.format(nome))
print('Olá {:>20}!'.format(nome))
print('Olá {:<20}!'.format(nome))
print('Olá {:^20}!'.format(nome))
print('Olá {:=^20}!'.format(nome))